### ISSUE TITLE
Generating documentation?

### ISSUE THREAD

**Issue by immitev** [ncbi/robotframework-pageobjects#15]
Hi,

I am playing with demo/pubmed and trying to generate XML documentation to import in RIDE via the command  "python -m robot.libdoc pubmed.py pubmed.xml". 

But I am getting as a result not what I would expect:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<keywordspec generated="20150311 14:26:58" type="library" name="pubmed" format="ROBOT">
<version></version>
<scope>global</scope>
<namedargs>yes</namedargs>
<doc>Documentation for test library `pubmed`.</doc>
<kw name="Robot Alias">
<arguments>
<arg>stub</arg>
</arguments>
<doc>Decorator function to wrap _Keywords.robot_alias
:param stub: The name of the original function (optionally containing a placeholder)
:type stub: str
:returns: callable</doc>
</kw>
</keywordspec>
```
Am I doing something wrong?

Best Regards

**Comment by hellmanj** [comment]
I think when you listed the .py file containing the Pubmed Page Objects, libdoc interpreted that as a module which is a library, when really it is a module containing several libraries.

So  "python -m robot.libdoc pubmed.PubmedHomePage pubmedhomepage.xml" is what you should do instead.

**Comment by immitev** [comment]
Thanks, that worked!
