### ISSUE TITLE
base_url is getting clobbered in my class

### ISSUE THREAD

**Issue by boakley** [ncbi/robotframework-pageobjects#20]
It seems like my base_url attribute is getting clobbered. My class starts like this:

```
from robotpageobjects import Page
class DashboardPage(Page):
    '''This is the documentation for OptimizerPage'''
    baseurl = "https://qa.example.com"
    def wait_for_ready_state(self, state="complete"):
        while (self.execute_javascript("return document.readyState") != state):
            time.sleep(0.5)
        return self
```

However, when I run my test I get `UriResolutionError: To open page object, "LoginPage" you must set a baseurl.`

The problem seems to be this line in base.py, in the constructor for `_BaseActions`:

    self.baseurl = self._option_handler.get("baseurl")

In my case, this is resetting `self.baseurl` to the empty string. Shouldn't that line of code only run if `self.baseurl` is undefined?

**Comment by frishberg** [comment]
Yes, right now we don't have a way of allowing declarative default options in page object classes. Here's something I suggested when we were developing this internally at NCBI:

> This is not necessarily a problem that needs solving yet, but it sort of came up for me just now. In BaseActions's _init_, we hardcode defaults like this:
> 
> self.browser = self._option_handler.get("browser") or "phantomjs"
> 
> What if you want your page object, say NCBIPage, to set its own default but still allow options to override it? Right now you have to do:
> 
> self.baseurl = self._option_handler.get("baseurl") or "http://www.ncbi.nlm.nih.gov"
> 
> It would be nice if there were some way to set a default. One idea would be to declare a class variable, "defaults":
> 
> class NCBIPage(Page):
>    ...
>    defaults = {
>        "baseurl": "http://www.ncbi.nlm.nih.gov"
>    }
>    ...
>
> Then robotpageobjects.Page's _init_ would fall back to defaults after checking options.

**Comment by kahunacohen** [comment]
@boakley: Pull requests are welcome. We'd be happy to review and work with you on any code suggestions you have. Thanks!

**Comment by kahunacohen** [comment]
I think the latest version addresses this issue. You can now set a class-level dict called options on your page object to set defaults. Is that right @hellmanj

**Comment by hellmanj** [comment]
Yes, I forgot about this issue, the commits should have referenced it since it's the same problem.

**Comment by hellmanj** [comment]
Fixed in https://github.com/ncbi/robotframework-pageobjects/pull/34
