### ISSUE TITLE
Change the way Page decides to use sauce

### ISSUE THREAD

**Issue by kahunacohen** [ncbi/robotframework-pageobjects#32]
Currently Page tries to open in sauce if sauce_username and sauce_apikey are set. Not sure this is right because it makes it hard to persist sauce username and api keys without always attempting to run in sauce.

Perhaps we should also check that sauce_platform and browser are set, because I think these along with sauce_username and apikey are the minimum needed to run in sauce.

**Comment by hellmanj** [comment]
So it sounds like sauce_platform is the real trigger to run in sauce then.  Or should we just have an explicit use_sauce option?

**Comment by kahunacohen** [comment]
I think it should be the minimum options that sauce needs which are browser, sauce_platform, sauce_username and sauce_apikey. Does that make sense? The rest of the sauce options are optional and if you have these 4 options set it's a safe bet you want to use sauce. This will allow us to persist sauce_username and sauce_apikey but also allow runs that are not in sauce if sauce_platform and browser are not set.

**Comment by hellmanj** [comment]
Yes, sounds good to me.
