### ISSUE TITLE
Open browser as maximized instead of 1920x1080

### ISSUE THREAD

**Issue by s4int** [ncbi/robotframework-pageobjects#39]
I had some problems running robot with page objects on Xvfb, my default resolution is 1280x1024. - As 
a result screenshots were cropped.

My proposition is to change
self.set_window_size(1920, 1080)
to:
self.maximize_browser_window()

On line:
https://github.com/ncbi/robotframework-pageobjects/blob/master/robotpageobjects/page.py#L594

If someone wants to use different resolution that his desktop or grid resolution than he should explicitly set it in test setup with "Set Window Size" keyword.

**Comment by kahunacohen** [comment]
Not sure of the implications of this. There's a reason we maximize, but I don't remember why. @hellmanj ?

**Comment by hellmanj** [comment]
I think we were having trouble with element visibility in phantomjs because the default window size is so small.  But @s4int is probably right that it's not this package's job to solve that problem.

**Comment by kahunacohen** [comment]
Why not leave the browser open as default and leave it to the user. In our base page object at NCBI we can maximize if we want. Is that a possibility @hellmanj ? Will that break any of our tests for RFPO?

**Comment by hellmanj** [comment]
That's what was suggested and I'm saying I agree, I'll give it a try.
