### ISSUE TITLE
release as wheel, avoid packit based pbr version conflicts for users

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ncbi/robotframework-pageobjects#50]
this would make installation via pip a lot more reliable,

since pbr version conflicts based on packit would no longer happen
(a whl installation does not run any python code of the project,
its just unpacking, and byte-code compilation)

**Comment by kahunacohen** [comment]
Hi @hellmanj do you have time to address this and/or respond? Thanks.

**Comment by hellmanj** [comment]
Yeah, I'll get an opinion from the packit guys.

**Comment by kahunacohen** [comment]
Thanks

**Comment by hellmanj** [comment]
@RonnyPfannschmidt, it shouldn't be a problem to release a wheel, I'll look into that tonight.  We're curious about your setup though.  Have you installed pbr system-wide? Or do you use other packages built with pbr? What packages? Which version of pbr do you have a conflict with?

**Comment by RonnyPfannschmidt** [comment]
packit depends on a very specific and outdated version of pbr, setup_requires creates quite a mess there

this was i particular a problem since another package we needed depended on a recent verison of pbr

in order to avoid the whole problem with nested setup requires i had to install different pinned versions of pbr in the test prepare process on the ci server, thats just a major pain

**Comment by hellmanj** [comment]
Okay, we're going to stick with packit for now.  A new version of it just came out which works with the current version of pbr.  We've also started releasing wheels.  Hopefully, this will not be an issue very often but we'll do our best to stay on top of any related issues.  Thanks again for the report.

**Comment by RonnyPfannschmidt** [comment]
using wheels completely solves the issue already, since a wheel installation will not require packit

thanks for your effort

**Comment by hellmanj** [comment]
Good point :)
