### ISSUE TITLE
Can't install robotframework-pageobjects with 'pip' on Windows

### ISSUE THREAD

**Issue by immitev** [ncbi/robotframework-pageobjects#52]
Tried to install with 'pip' but couldn't. Using Windows 8. 
When ran with non-admin got several errors "WindowsError: [Error 2] The system cannot find the file specified".
When ran as admin, the installation never completes (at least several hours).

Installed packages (Python 2.7):

Paver==1.2.4
Pygments==2.0.2
decorator==3.4.2
docutils==0.12
mock==1.0.1
nose==1.3.7
packit==0.9.2
requests==2.7.0
robotframework==2.8.7
robotframework-selenium2library==1.7.1
selenium==2.46.0
wheel==0.24.0

**Comment by kahunacohen** [comment]
We are not supporting this package on Windows. We don't use Windows and don't have the bandwidth to do so. Pull requests, however, are always welcome. We'd be glad to review if you or someone else would like to make this package compatible with Windows.

**Comment by zlorb** [comment]
The following seemed to work on Windows (8.1), w/o requiring code changes. 
Did not test this much, but these steps allowed to use both pip install as well as building the package from the latest git snapshot (1.3.3).
- Install all individual items listed in `requirements.txt` ; example: pip install --upgrade uritemplate
- Install git: https://github.com/git-for-windows/git/releases
- Install gitpython: https://github.com/gitpython-developers/GitPython
- Make sure `git.exe` is in the path.

**Comment by immitev** [comment]
I can also confirm that with the latest couple of versions of the library, the robotframework-pageobjects installation with 'pip'  on Windows (both Win7 and Win8.1) was fine.
